package notifications

import (
	"fmt"
	"time"
)

// Title formats a notification title as "hostname: slug".
func Title(hostname, slug string) string {
	if hostname != "" && slug != "" {
		return fmt.Sprintf("%s: %s", hostname, slug)
	}
	if hostname != "" {
		return hostname
	}
	if slug != "" {
		return slug
	}
	return "Shelley"
}

// EventType identifies the kind of notification event.
type EventType string

const (
	EventAgentDone  EventType = "agent_done"
	EventAgentError EventType = "agent_error"
)

// Event is a notification event generated by the system.
type Event struct {
	Type           EventType `json:"type"`
	ConversationID string    `json:"conversation_id"`
	Timestamp      time.Time `json:"timestamp"`
	Payload        any       `json:"payload,omitempty"`
}

// AgentDonePayload is the payload for EventAgentDone.
type AgentDonePayload struct {
	Hostname          string `json:"hostname,omitempty"`
	Model             string `json:"model,omitempty"`
	ConversationTitle string `json:"conversation_title,omitempty"`
	ConversationURL   string `json:"conversation_url,omitempty"`
	VMName            string `json:"vm_name,omitempty"`
	FinalResponse     string `json:"final_response,omitempty"`
}

// AgentErrorPayload is the payload for EventAgentError.
type AgentErrorPayload struct {
	Hostname        string `json:"hostname,omitempty"`
	ErrorMessage    string `json:"error_message"`
	ConversationURL string `json:"conversation_url,omitempty"`
}
