package server

import (
	"bytes"
	"go/parser"
	"go/token"
	"path/filepath"
	"strings"
)

// IsAutogeneratedPath reports whether a file path suggests it's autogenerated.
// This checks for common autogenerated file patterns based on path alone.
func IsAutogeneratedPath(path string) bool {
	base := filepath.Base(path)

	// Convert path separators to forward slashes for consistent matching
	normPath := filepath.ToSlash(path)

	// Check directory patterns first
	// We check if any path component matches the autogenerated directory name
	for _, d := range autogeneratedDirs {
		// Match at start of path or after a /
		if strings.HasPrefix(normPath, d) || strings.Contains(normPath, "/"+d) {
			return true
		}
	}

	// Check file extension patterns
	for _, ext := range autogeneratedExtensions {
		if strings.HasSuffix(base, ext) {
			return true
		}
	}

	// Check exact filename matches
	for _, name := range autogeneratedFilenames {
		if base == name {
			return true
		}
	}

	return false
}

// IsAutogeneratedFile reports whether a file is autogenerated based on its path and content.
// For Go files, it also analyzes the content for autogeneration markers.
func IsAutogeneratedFile(path string, content []byte) bool {
	if IsAutogeneratedPath(path) {
		return true
	}

	// For Go files, check content for autogeneration markers
	if strings.HasSuffix(path, ".go") && content != nil {
		return isAutogeneratedGoContent(content)
	}

	return false
}

// isAutogeneratedGoContent reports whether a Go file has markers indicating it was autogenerated.
func isAutogeneratedGoContent(buf []byte) bool {
	for _, sig := range autogeneratedSignals {
		if bytes.Contains(buf, sig) {
			return true
		}
	}

	// https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source
	// "This line must appear before the first non-comment, non-blank text in the file."
	// Approximate that by looking for it at the top of the file, before the last of the imports.
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "x.go", buf, parser.ImportsOnly|parser.ParseComments)
	if err == nil {
		for _, cg := range f.Comments {
			t := strings.ToLower(cg.Text())
			for _, sig := range autogeneratedHeaderSignals {
				if strings.Contains(t, sig) {
					return true
				}
			}
		}
	}

	return false
}

// autogeneratedDirs are directory names that typically contain generated files.
var autogeneratedDirs = []string{
	"vendor/",
	"node_modules/",
	".git/",
	"__pycache__/",
	".next/",
	"dist/",
	"build/",
	"generated/",
	"gen/",
}

// autogeneratedExtensions are file suffixes that indicate autogenerated files.
var autogeneratedExtensions = []string{
	".pb.go",        // Protocol buffers
	".pb.gw.go",     // gRPC gateway
	"_string.go",    // stringer
	".gen.go",       // general generated Go
	".generated.go", // general generated Go
	"_generated.go", // general generated Go
	".mock.go",      // mocks
	"_mock.go",      // mocks
	".mocks.go",     // mocks
	"_mocks.go",     // mocks
	".min.js",       // minified JS
	".min.css",      // minified CSS
	".d.ts",         // TypeScript declarations
	".pb.ts",        // Protocol buffers TypeScript
	".generated.ts", // general generated TypeScript
	"_generated.ts", // general generated TypeScript
	".sql.go",       // sqlc generated
	".enumer.go",    // enumer generated
	"_easyjson.go",  // easyjson generated
	".deepcopy.go",  // Kubernetes deepcopy
}

// autogeneratedFilenames are exact filenames that are typically autogenerated.
var autogeneratedFilenames = []string{
	"go.sum",
	"package-lock.json",
	"yarn.lock",
	"pnpm-lock.yaml",
	"Cargo.lock",
	"Gemfile.lock",
	"composer.lock",
	"poetry.lock",
	"uv.lock",
}

// autogeneratedSignals are signals that a Go file is autogenerated, when present anywhere in the file.
var autogeneratedSignals = [][]byte{
	[]byte("\nfunc bindataRead("), // pre-embed bindata packed file
}

// autogeneratedHeaderSignals are signals that a file is autogenerated, when present at the top of the file.
var autogeneratedHeaderSignals = []string{
	// canonical would be `(?m)^// Code generated .* DO NOT EDIT\.$`
	// but people screw it up, a lot, so be more lenient
	strings.ToLower("generate"),
	strings.ToLower("DO NOT EDIT"),
	strings.ToLower("export by"),
}
